<?php
return [
    'type'            => $_ENV['DATABASE_TYPE'] ?? 'mysql',
    'hostname'        => $_ENV['DATABASE_HOSTNAME'] ?? '127.0.0.1',
    'database'        => $_ENV['DATABASE_DATABASE'] ?? 'chemdoc',
    'username'        => $_ENV['DATABASE_USERNAME'] ?? 'root',
    'password'        => $_ENV['DATABASE_PASSWORD'] ?? 'root',
    'hostport'        => $_ENV['DATABASE_HOSTPORT'] ?? '3306',
    'charset'         => $_ENV['DATABASE_CHARSET'] ?? 'utf8mb4',
    'prefix'          => $_ENV['DATABASE_PREFIX'] ?? '',
    'debug'           => ($_ENV['DATABASE_DEBUG'] ?? 'true') === 'true',
    'deploy'          => 0,
    'rw_separate'     => false,
    'master_num'      => 1,
    'slave_no'        => '',
    'fields_strict'   => true,
    'fields_cache'     => false,
    'trigger_sql'      => true,
    'break_reconnect'  => false,
    'break_match_str'  => [],
    'resultset_type'  => 'array',
    'auto_timestamp'   => false,
    'datetime_format' => 'Y-m-d H:i:s',
    'sql_explain'     => false,
    'query'           => '\\think\\db\\Query',
    'builder'         => '',
];
